<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace GPBMetadata;

class Msg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a380a096d73672e70726f746f22230a036d7367120b0a036d7367180120" .
            "012809120f0a0776657273696f6e180220012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

